apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }} # my-helm-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }} # my-helm-app
spec:
  ports:
  - port: 5000 # bring the traffic!
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }} # my-helm-app
    tier: frontend
  type: LoadBalancer